<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace local_coursegen\mod_settings;

use context_module;
use gradingform_controller;
use stdClass;

/**
 * Class assign_settings
 *
 * Creates the grading rubric generated by the AI service after the assignment
 * instance exists. When the payload carries a rubric, it is registered as the
 * advanced grading method for the assignment's "submissions" area and its
 * criteria/levels are written through the native gradingform_rubric controller.
 * When no rubric is present the class does nothing (simple point grading is kept).
 *
 * @package    local_coursegen
 * @copyright  2026 Wilber Narvaez <https://datacurso.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class assign_settings extends base_settings {
    /**
     * Create the rubric grading definition, when one was generated.
     */
    public function add_settings() {
        global $CFG;

        $rubric = $this->modsettings['rubric'] ?? null;
        if (empty($rubric) || empty($rubric['criteria'])) {
            return;
        }

        $criteria = $this->build_criteria($rubric['criteria']);
        if (empty($criteria)) {
            return;
        }

        require_once($CFG->dirroot . '/grade/grading/lib.php');

        $context = context_module::instance($this->cm->coursemodule);

        // Order mirrors core\'s core_grading_external::save_definitions: activate the method on the
        // area first (creates the area if needed), then write the definition through its controller.
        $gradingmanager = get_grading_manager($context, 'mod_assign', 'submissions');
        $gradingmanager->set_active_method('rubric');
        $controller = $gradingmanager->get_controller('rubric');

        $definition = new stdClass();
        $definition->name = $this->rubric_name($rubric);
        // file_postupdate_standard_editor (called inside the controller) requires the editor field.
        $definition->description_editor = ['text' => '', 'format' => FORMAT_HTML, 'itemid' => 0];
        // READY so the rubric is usable immediately; an empty status would persist as DRAFT.
        $definition->status = gradingform_controller::DEFINITION_STATUS_READY;
        $definition->rubric = ['criteria' => $criteria];

        $controller->update_definition($definition);
    }

    /**
     * Map the AI criteria to the structure update_definition() expects.
     *
     * New rows/columns are keyed with NEWID<n> so the controller inserts them. Criteria with no
     * description or fewer than two valid levels are skipped (a rubric criterion needs >= 2 levels).
     *
     * @param array $criteriain AI criteria (each: description + levels).
     * @return array Criteria keyed by NEWID<n>.
     */
    protected function build_criteria(array $criteriain): array {
        $criteria = [];
        $cindex = 0;
        foreach ($criteriain as $criterion) {
            $description = trim((string) ($criterion['description'] ?? ''));
            $levelsin = $criterion['levels'] ?? [];
            if ($description === '' || empty($levelsin)) {
                continue;
            }
            $levels = $this->build_levels($levelsin);
            if (count($levels) < 2) {
                continue;
            }
            $cindex++;
            $criteria['NEWID' . $cindex] = [
                'sortorder' => $cindex,
                'description' => $description,
                'descriptionformat' => FORMAT_MOODLE,
                'levels' => $levels,
            ];
        }
        return $criteria;
    }

    /**
     * Map the levels of one criterion to the NEWID structure.
     *
     * @param array $levelsin AI levels (each: definition + points).
     * @return array Levels keyed by NEWID<n>.
     */
    protected function build_levels(array $levelsin): array {
        $levels = [];
        $lindex = 0;
        foreach ($levelsin as $level) {
            $definition = trim((string) ($level['definition'] ?? ''));
            if ($definition === '') {
                continue;
            }
            $lindex++;
            $levels['NEWID' . $lindex] = [
                'definition' => $definition,
                'definitionformat' => FORMAT_MOODLE,
                'score' => (float) ($level['points'] ?? 0),
            ];
        }
        return $levels;
    }

    /**
     * Resolve the rubric name, falling back to the rubric plugin name.
     *
     * @param array $rubric The rubric payload.
     * @return string
     */
    protected function rubric_name(array $rubric): string {
        $name = trim((string) ($rubric['name'] ?? ''));
        if ($name !== '') {
            return $name;
        }
        return get_string('pluginname', 'gradingform_rubric');
    }
}
