<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace local_coursegen\mod_settings;

use stdClass;

/**
 * Class data_settings
 *
 * Creates the database fields (columns) generated by the AI service after the database instance
 * exists. The standard module creation cannot create fields, so without this a database activity
 * has no columns and is unusable. Each definition is written through mod_data's native field API
 * (data_get_field_new -> define_field -> insert_field). The list/single/add/search templates are
 * generated lazily by mod_data the first time they are rendered (manager::get_template falls back
 * to data_generate_default_template when a stored template is empty), exactly as for a database a
 * teacher builds by hand, so no template needs to be persisted here. When no fields are present
 * the class does nothing.
 *
 * @package    local_coursegen
 * @copyright  2026 Wilber Narvaez <https://datacurso.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class data_settings extends base_settings {

    /** @var string[] Field types that store their choices, one per line, in param1. */
    private const CHOICE_TYPES = ['menu', 'multimenu', 'radiobutton', 'checkbox'];

    /**
     * Per-type param defaults applied when creating a field programmatically.
     *
     * Creating a field by code skips the edit form, so type params start empty. For most types
     * that is fine, but a few render poorly without them, so we replicate mod_data's own form
     * defaults: textarea would otherwise be a tiny box with no editor, picture would show
     * full-resolution images in lists, and a url would not be a clickable link.
     *
     * @var array<string, array<string, string>>
     */
    private const TYPE_DEFAULTS = [
        // param2 = columns, param3 = rows, param4 = use HTML editor, param5 = max size (0 = none).
        'textarea' => ['param2' => '60', 'param3' => '35', 'param4' => '1', 'param5' => '0'],
        // param1/param2 = list thumbnail width/height, param4/param5 = single-view width/height.
        'picture'  => ['param1' => '100', 'param2' => '200', 'param4' => '300', 'param5' => '400'],
        // param1 = autolink (make the URL a clickable link).
        'url'      => ['param1' => '1'],
    ];

    /**
     * Create the database fields, when any were generated.
     */
    public function add_settings() {
        global $CFG, $DB;

        $fields = $this->modsettings['fields'] ?? [];
        if (empty($fields) || !is_array($fields)) {
            return;
        }

        $dataid = (int) ($this->cm->instance ?? 0);
        if (!$dataid) {
            return;
        }

        require_once($CFG->dirroot . '/mod/data/lib.php');

        $datainstance = $DB->get_record('data', ['id' => $dataid]);
        if (!$datainstance) {
            return;
        }

        foreach ($fields as $fieldspec) {
            if (is_array($fieldspec)) {
                $this->create_field($datainstance, $fieldspec);
            }
        }
    }

    /**
     * Create a single field from its AI definition.
     *
     * Invalid definitions are skipped rather than failing the whole activity: an empty name or
     * type, a duplicate name (the module requires unique field names), an unknown field type, or
     * a choice field with no options.
     *
     * @param stdClass $datainstance The database activity record.
     * @param array $spec The field definition (type, name, description, required, options).
     */
    protected function create_field(stdClass $datainstance, array $spec): void {
        $type = trim((string) ($spec['type'] ?? ''));
        $name = trim((string) ($spec['name'] ?? ''));
        if ($type === '' || $name === '') {
            return;
        }
        if (data_fieldname_exists($name, $datainstance->id)) {
            return;
        }

        $formdata = $this->build_formdata($type, $name, $spec);
        // A choice field with no usable options cannot be filled in -> skip it.
        if (in_array($type, self::CHOICE_TYPES, true) && trim((string) ($formdata->param1 ?? '')) === '') {
            return;
        }

        // A single problematic field (unknown/disabled type, a DB error, an over-long name, ...)
        // must never abort the activity creation or the remaining fields: this runs after the
        // module already exists, so a thrown error would leave a half-built database.
        try {
            $field = data_get_field_new($type, $datainstance);
            $field->define_field($formdata);
            $field->insert_field();
        } catch (\Throwable $e) {
            debugging(
                'local_coursegen: skipped data field "' . $name . '": ' . $e->getMessage(),
                DEBUG_DEVELOPER
            );
        }
    }

    /**
     * Build the form-data object define_field() expects from the AI field definition.
     *
     * @param string $type The Moodle field type.
     * @param string $name The (validated) field name.
     * @param array $spec The field definition.
     * @return stdClass
     */
    protected function build_formdata(string $type, string $name, array $spec): stdClass {
        $formdata = new stdClass();
        $formdata->name = $name;
        $formdata->description = trim((string) ($spec['description'] ?? ''));
        $formdata->required = !empty($spec['required']) ? 1 : 0;

        foreach (self::TYPE_DEFAULTS[$type] ?? [] as $param => $value) {
            $formdata->$param = $value;
        }

        if (in_array($type, self::CHOICE_TYPES, true)) {
            // menu/multimenu/radiobutton/checkbox read their options from param1, one per line.
            $formdata->param1 = implode("\n", $this->clean_options($spec['options'] ?? []));
        }

        return $formdata;
    }

    /**
     * Trim and drop blank entries from a list of choice options.
     *
     * @param mixed $options
     * @return string[]
     */
    protected function clean_options($options): array {
        if (!is_array($options)) {
            return [];
        }
        $clean = [];
        foreach ($options as $option) {
            $option = trim((string) $option);
            if ($option !== '') {
                $clean[] = $option;
            }
        }
        return $clean;
    }
}
