<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace local_coursegen\mod_settings;

/**
 * Class workshop_settings
 *
 * Inserts the accumulative assessment-form criteria generated by the AI so the
 * workshop's assessment form is ready (a workshop with no criteria cannot be
 * assessed by reviewers), and optionally switches the freshly created workshop
 * to the initial phase requested by the AI (submission, assessment or
 * evaluation); the Moodle default (setup) is kept otherwise.
 *
 * @package    local_coursegen
 * @copyright  2026 Wilber Narvaez <https://datacurso.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class workshop_settings extends base_settings {
    /** @var int[] Map of AI phase tokens to workshop phase constants (setup is the default, closed unsupported). */
    private const PHASE_MAP = [
        'submission' => 20, // \workshop::PHASE_SUBMISSION.
        'assessment' => 30, // \workshop::PHASE_ASSESSMENT.
        'evaluation' => 40, // \workshop::PHASE_EVALUATION.
    ];

    /**
     * Add the AI-generated accumulative criteria to the workshop assessment form
     * and apply the requested initial phase, if any.
     */
    public function add_settings() {
        $this->add_criteria();
        $this->apply_initial_phase();
    }

    /**
     * Insert the AI-generated accumulative criteria rows.
     */
    private function add_criteria(): void {
        global $DB;

        $criteria = $this->modsettings['criteria'] ?? [];
        if (empty($criteria)) {
            return;
        }

        $sort = 1;
        foreach ($criteria as $criterion) {
            $description = trim((string) ($criterion['description'] ?? ''));
            if ($description === '') {
                continue;
            }
            $maxpoints = (int) ($criterion['max_points'] ?? 10);
            if ($maxpoints < 1) {
                $maxpoints = 10;
            }

            $record = (object) [
                'workshopid' => $this->cm->instance,
                'sort' => $sort,
                'description' => $description,
                'descriptionformat' => FORMAT_HTML,
                'grade' => $maxpoints,
                'weight' => 1,
            ];
            $DB->insert_record('workshopform_accumulative', $record);
            $sort++;
        }
    }

    /**
     * Switch the workshop to the initial phase requested by the AI service.
     *
     * The Moodle default (setup) is kept when the token is absent, null or
     * 'setup'. Unknown tokens and any runtime failure while switching are
     * reported via debugging() and ignored so the module creation never fails
     * because of phase handling.
     */
    private function apply_initial_phase(): void {
        global $CFG, $DB;

        $token = $this->modsettings['initial_phase'] ?? null;
        if ($token === null || $token === '' || $token === 'setup') {
            return;
        }

        if (!is_string($token) || !isset(self::PHASE_MAP[$token])) {
            $tokenlabel = is_string($token) ? $token : gettype($token);
            debugging(
                "local_coursegen: unknown workshop initial_phase '{$tokenlabel}'; keeping the setup phase.",
                DEBUG_DEVELOPER
            );
            return;
        }
        $targetphase = self::PHASE_MAP[$token];

        require_once($CFG->dirroot . '/mod/workshop/locallib.php');

        try {
            $record = $DB->get_record('workshop', ['id' => $this->cm->instance], '*', MUST_EXIST);
            [$course, $cm] = get_course_and_cm_from_cmid($this->cm->coursemodule, 'workshop');

            $workshop = new \workshop($record, $cm, $course);
            if (!$workshop->switch_phase($targetphase)) {
                debugging(
                    "local_coursegen: could not switch workshop {$record->id} to phase '{$token}'.",
                    DEBUG_DEVELOPER
                );
            }
        } catch (\Throwable $e) {
            debugging('local_coursegen: failed to switch workshop phase: ' . $e->getMessage(), DEBUG_DEVELOPER);
        }
    }
}
