@local @local_coursegen @javascript @coursegen_requires_ai_service
Feature: AI activity generation end to end from the modal
  In order to obtain playable H5P activities generated by AI
  As a teacher
  I need the full generation flow to honour type, language, images and grading options

  # =========================================================================
  # SERVICE-DEPENDENT SCENARIOS — @coursegen_requires_ai_service
  #
  # Every scenario in this file needs the live DataCurso AI service:
  #   - a valid aiprovider_datacurso license key configured on the site, and
  #   - the service URLs reachable (defaults, or the local_coursegen
  #     datacurso_service_url / datacurso_service_url_eu dev overrides).
  #
  # They MUST be excluded in CI:
  #   vendor/bin/behat --tags='~@coursegen_requires_ai_service'
  #
  # They serve as scripted manual / E2E-with-service runs. Generation against
  # the live service takes minutes: run them with an increased step timeout
  # ($CFG->behat_increasetimeout) or follow them manually. The UI-reachable
  # halves of these spec IDs are runnable without the service and live in
  # activity_ai_modal.feature.
  # =========================================================================

  Background:
    Given the following "users" exist:
      | username | firstname | lastname | email                |
      | teacher1 | Teena     | Teacher  | teacher1@example.com |
      | student1 | Sam       | Student  | student1@example.com |
    And the following "courses" exist:
      | fullname | shortname | category |
      | Course 1 | C1        | 0        |
    And the following "course enrolments" exist:
      | user     | course | role           |
      | teacher1 | C1     | editingteacher |
      | student1 | C1     | student        |

  @SYS-E2E-001
  Scenario: Create a question set naming the type and the passing grade from the modal
    Given I am on the "Course 1" course page logged in as teacher1
    And I turn editing mode on
    And I click on "Add activity or resource with AI" "button"
    When I set the field "Describe what you need" to "Create a question set about the water cycle with 4 questions and a passing grade of 80"
    And I click on "button[title='Send']" "css_element" in the "Create resource/activity with AI" "dialogue"
    Then I should see "You asked:" in the "Create resource/activity with AI" "dialogue"
    And I should see "Waiting for your review." in the "Create resource/activity with AI" "dialogue"
    When I click on "Accept and create activity" "button" in the "Create resource/activity with AI" "dialogue"
    Then I should see "Plan accepted. Generating..." in the "Create resource/activity with AI" "dialogue"
    # On completion the browser is redirected to the created H5P activity.
    And "#page-mod-h5pactivity-view" "css_element" should exist
    # Manual verification (H5P content plays inside an iframe; no standard
    # steps can drive it):
    #   1. Log in as student1, open the created activity and complete an attempt.
    #   2. In the gradebook check: Maximum grade 100, Grading method
    #      "Highest grade", Grade to pass 80, and the attempt grade recorded.

  @SYS-E2E-002
  Scenario: Create a visual type from the modal with image generation enabled
    Given I am on the "Course 1" course page logged in as teacher1
    And I turn editing mode on
    And I click on "Add activity or resource with AI" "button"
    When I click on "input[name='generate_images'][value='1']" "css_element" in the "Create resource/activity with AI" "dialogue"
    And I set the field "Describe what you need" to "Create a memory game about farm animals"
    And I click on "button[title='Send']" "css_element" in the "Create resource/activity with AI" "dialogue"
    Then I should see "Waiting for your review." in the "Create resource/activity with AI" "dialogue"
    When I click on "Accept and create activity" "button" in the "Create resource/activity with AI" "dialogue"
    Then "#page-mod-h5pactivity-view" "css_element" should exist
    # Manual verification:
    #   1. Play the activity: all cards must render their images (no broken
    #      resources) — images must be embedded inside the .h5p package, in a
    #      format allowed by the Moodle file type whitelist.

  @SYS-E2E-003
  Scenario Outline: The activity type named by the teacher is honoured end to end
    Given I am on the "Course 1" course page logged in as teacher1
    And I turn editing mode on
    And I click on "Add activity or resource with AI" "button"
    When I set the field "Describe what you need" to "<prompt>"
    And I click on "button[title='Send']" "css_element" in the "Create resource/activity with AI" "dialogue"
    Then I should see "Waiting for your review." in the "Create resource/activity with AI" "dialogue"
    When I click on "Accept and create activity" "button" in the "Create resource/activity with AI" "dialogue"
    Then "#page-mod-h5pactivity-view" "css_element" should exist
    # Manual verification: download the attached .h5p package and check
    # h5p.json mainLibrary is exactly the requested content type
    # (Crossword, Find The Words, Accordion, Flashcards) with no drift to a
    # similar type.

    Examples:
      | prompt                                                        |
      | Crea un crucigrama sobre las capitales de Europa              |
      | Crea una sopa de letras sobre los planetas del sistema solar  |
      | Create an accordion about the layers of the atmosphere        |
      | Create flashcards about basic French vocabulary               |

  @SYS-E2E-004
  Scenario Outline: The content follows the language selected in the modal
    Given I am on the "Course 1" course page logged in as teacher1
    And I turn editing mode on
    And I click on "Add activity or resource with AI" "button"
    When I set the field with xpath "//select[@data-region='local_coursegen/activity/lang']" to "<lang>"
    And I set the field "Describe what you need" to "Create an accordion about photosynthesis"
    And I click on "button[title='Send']" "css_element" in the "Create resource/activity with AI" "dialogue"
    Then I should see "Waiting for your review." in the "Create resource/activity with AI" "dialogue"
    When I click on "Accept and create activity" "button" in the "Create resource/activity with AI" "dialogue"
    Then "#page-mod-h5pactivity-view" "css_element" should exist
    # Manual verification: play the activity — the generated content AND the
    # H5P player interface labels must be in the selected language, with no
    # language mixing.

    Examples:
      | lang |
      | es   |
      | en   |

  @SYS-E2E-005
  Scenario: A type that honours the image toggle generates images when enabled
    Given I am on the "Course 1" course page logged in as teacher1
    And I turn editing mode on
    And I click on "Add activity or resource with AI" "button"
    When I click on "input[name='generate_images'][value='1']" "css_element" in the "Create resource/activity with AI" "dialogue"
    And I set the field "Describe what you need" to "Create a timeline about the history of computing with 5 events"
    And I click on "button[title='Send']" "css_element" in the "Create resource/activity with AI" "dialogue"
    Then I should see "Waiting for your review." in the "Create resource/activity with AI" "dialogue"
    When I click on "Accept and create activity" "button" in the "Create resource/activity with AI" "dialogue"
    Then "#page-mod-h5pactivity-view" "css_element" should exist
    # Manual verification: the timeline events include generated images.

  @SYS-E2E-005
  Scenario: A type that honours the image toggle generates no images when disabled
    Given I am on the "Course 1" course page logged in as teacher1
    And I turn editing mode on
    And I click on "Add activity or resource with AI" "button"
    # "Do not generate images" is the default (verified as runnable in
    # activity_ai_modal.feature), so the toggle is left untouched.
    When I set the field "Describe what you need" to "Create a timeline about the history of computing with 5 events"
    And I click on "button[title='Send']" "css_element" in the "Create resource/activity with AI" "dialogue"
    Then I should see "Waiting for your review." in the "Create resource/activity with AI" "dialogue"
    When I click on "Accept and create activity" "button" in the "Create resource/activity with AI" "dialogue"
    Then "#page-mod-h5pactivity-view" "css_element" should exist
    # Manual verification: no event in the timeline carries a generated image.

  @SYS-E2E-005
  Scenario: A visual type that does not honour the image toggle today (documented behaviour)
    Given I am on the "Course 1" course page logged in as teacher1
    And I turn editing mode on
    And I click on "Add activity or resource with AI" "button"
    When I set the field "Describe what you need" to "Create a memory game about farm animals"
    And I click on "button[title='Send']" "css_element" in the "Create resource/activity with AI" "dialogue"
    Then I should see "Waiting for your review." in the "Create resource/activity with AI" "dialogue"
    When I click on "Accept and create activity" "button" in the "Create resource/activity with AI" "dialogue"
    Then "#page-mod-h5pactivity-view" "css_element" should exist
    # NOTA [Pendiente:skip] (SYS-E2E-005): with the toggle off, the memory game
    # still generates images today, and the personality quiz always generates
    # its cover image even when the rest honours the toggle — current behaviour
    # documented in the scope. When the fix lands, this manual check must flip
    # to: the memory game creates NO images with the toggle off.
    # NOTA [Pendiente:skip] (SYS-E2E-005): the admin per-activity-type image
    # configuration only travels in the full-course flow; the individual
    # generation sends only the modal option.

  @SYS-E2E-007
  Scenario: The generated package uses the library set matching the site H5P framework
    # Environment-dependent: run this same scenario on a Moodle 4.5 site and on
    # a Moodle 5.x site (different core H5P framework versions). It cannot be
    # automated on a single CI site.
    Given I am on the "Course 1" course page logged in as teacher1
    And I turn editing mode on
    And I click on "Add activity or resource with AI" "button"
    When I set the field "Describe what you need" to "Create an accordion about the layers of the atmosphere"
    And I click on "button[title='Send']" "css_element" in the "Create resource/activity with AI" "dialogue"
    Then I should see "Waiting for your review." in the "Create resource/activity with AI" "dialogue"
    When I click on "Accept and create activity" "button" in the "Create resource/activity with AI" "dialogue"
    Then "#page-mod-h5pactivity-view" "css_element" should exist
    # Manual verification (per site): the plugin sends the site H5P core API
    # version (h5p_core_api) with the request; the service must package the
    # library set matching that version (v127 vs v128 sets). Compare the
    # library versions inside each downloaded .h5p and confirm both packages
    # play without errors on their own site.

  @SYS-E2E-008
  Scenario: A service validation error is reported with an actionable message and retry works
    # Provoke a validation error from the live service when starting the
    # generation (for example a mandatory request field missing due to
    # incomplete site configuration — the missing site address regression).
    Given I am on the "Course 1" course page logged in as teacher1
    And I turn editing mode on
    And I click on "Add activity or resource with AI" "button"
    When I set the field "Describe what you need" to "Create a quiz about renewable energy"
    And I click on "button[title='Send']" "css_element" in the "Create resource/activity with AI" "dialogue"
    Then "[data-region='local_coursegen/activity/retry-alert']" "css_element" should exist in the "Create resource/activity with AI" "dialogue"
    # Target behaviour (per the scope): the teacher sees an actionable message
    # describing the failed validation — NOT a generic HTTP-code message — and
    # a "Retry" action that succeeds once the cause is fixed.
    # NOTA (documented defect): today the service validation detail is
    # discarded and only a generic message with the HTTP code reaches the
    # teacher, and init failures are not marked retriable. This scenario
    # scripts the target behaviour for the manual/with-service run; the
    # current error surface is asserted (runnable, without service) in
    # activity_ai_modal.feature.
